version: "3.8"

services:
  api:
    image: rg.fr-par.scw.cloud/rl-idle/api-stagging:latest
    container_name: rl-idle_api
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - "10057:3000"
    networks:
      - backend
      - frontend

  app:
    image: rg.fr-par.scw.cloud/rl-idle/app-stagging:latest
    container_name: rl-idle_app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - "10058:3000"
    networks:
      - frontend

  db:
    image: postgres:latest
    container_name: rl-idle_db
    restart: unless-stopped
    volumes:
      - rl-idle-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - "10059:5432"
    networks:
      - backend

  redis:
    restart: unless-stopped
    container_name: rl-idle_redis
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - rl-idle-redis-data:/data
    ports:
      - "10060:6379"
    networks:
      - backend

volumes:
  rl-idle-postgres-data:
  rl-idle-redis-data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
