version: "3.8"

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.


    ports:
      - 5432:5432  

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data

    # Add "forwardPorts": ["6379"] to **devcontainer.json** to forward Redis locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.

    ports:
      - 6379:6379

volumes:
  postgres-data:
  redis-data:
