name: deployment workflow rec

on:
  push:
    branches:
      - rec

  workflow_dispatch:

jobs:
  security:
    name: TruffleHog Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  run:
    environment: rec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env
        run: |
          touch .env
          echo ENV=production >> .env
          echo DATABASE_URL="postgresql://${{ vars.DATABASE_USER }}:${{ secrets.DATABASE_PASS }}@db:5432/${{ vars.DATABASE_NAME }}?schema=public" >> .env
          echo DATABASE_USER=${{ vars.DATABASE_USER }} >> .env
          echo DATABASE_PASS=${{ secrets.DATABASE_PASS }} >> .env
          echo DATABASE_NAME=${{ vars.DATABASE_NAME }} >> .env
          echo REDIS_HOST=localhost >> .env
          echo REDIS_USERNAME= >> .env
          echo REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} >> .env
          echo REDIS_PORT=6379 >> .env
          echo REDIS_URL=redis://redis:6379 >> .env
          echo REDIS_USE_TLS=false >> .env

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_KEY }}
          registry: rg.fr-par.scw.cloud/rl-idle

      - name: Build the docker image
        run: |
          # Api
          docker build -t rg.fr-par.scw.cloud/rl-idle/api:latest .
          docker push rg.fr-par.scw.cloud/rl-idle/api:latest

      - name: Push docker compose
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          ssh -p ${{ vars.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "mkdir -p ${{ secrets.SOURCE_PATH }}"
          mkdir -p tmp/rl-idle-devops
          git clone https://github.com/RL-IDLE/rl-idle-devops.git tmp/rl-idle-devops
          scp -P ${{ vars.SSH_PORT }} tmp/rl-idle-devops/docker/docker-compose.recette.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SOURCE_PATH }}/docker-compose.yml
          scp -P ${{ vars.SSH_PORT }} .env ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SOURCE_PATH }}/.env

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          envs: REGISTRY_USERNAME, REGISTRY_KEY
          script: |
            cd ${{ secrets.SOURCE_PATH }}
            set -a
            source .env
            docker login rg.fr-par.scw.cloud/rl-idle -u '${{ secrets.REGISTRY_USERNAME }}' -p '${{ secrets.REGISTRY_KEY }}'
            docker compose pull
            docker system prune -f
            docker compose up -d
